packages:
  - apps/*
  - packages/*

catalog:
  '@internationalized/date': 3.9.0
  '@biomejs/biome': 2.2.2
  '@faker-js/faker': 10.0.0
  '@playwright/test': 1.55.0
  '@radix-ui/react-accordion': 1.2.12
  '@radix-ui/react-alert-dialog': 1.1.15
  '@radix-ui/react-aspect-ratio': 1.1.7
  '@radix-ui/react-avatar': 1.1.10
  '@radix-ui/react-checkbox': 1.3.3
  '@radix-ui/react-collapsible': 1.1.12
  '@radix-ui/react-context-menu': 2.2.16
  '@radix-ui/react-dialog': 1.1.15
  '@radix-ui/react-dropdown-menu': 2.1.16
  '@radix-ui/react-hover-card': 1.1.15
  '@radix-ui/react-label': 2.1.7
  '@radix-ui/react-menubar': 1.1.16
  '@radix-ui/react-navigation-menu': 1.2.14
  '@radix-ui/react-popover': 1.1.15
  '@radix-ui/react-progress': 1.1.7
  '@radix-ui/react-radio-group': 1.3.8
  '@radix-ui/react-scroll-area': 1.2.10
  '@radix-ui/react-select': 2.2.5
  '@radix-ui/react-separator': 1.1.7
  '@radix-ui/react-slider': 1.3.6
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-switch': 1.2.6
  '@radix-ui/react-tabs': 1.1.13
  '@radix-ui/react-toggle': 1.1.10
  '@radix-ui/react-toggle-group': 1.1.11
  '@radix-ui/react-tooltip': 1.2.8
  '@react-email/components': 0.5.0
  '@react-email/preview-server': 4.2.8
  '@tailwindcss/typography': 0.5.16
  '@tailwindcss/vite': 4.1.12
  '@tanstack/react-form': 1.19.2
  '@tanstack/react-router': 1.130.12
  '@tanstack/react-start': 1.130.15
  '@tanstack/react-store': 0.7.4
  '@tiptap/core': 3.4.1
  '@tiptap/pm': 3.4.1
  '@tiptap/react': 3.4.1
  '@tiptap/starter-kit': 3.4.1
  '@types/node': 24.2.1
  '@types/nodemailer': 6.4.17
  '@types/pg': 8.15.5
  '@types/prompts': 2.4.9
  '@types/react': 19.1.9
  '@types/react-dom': 19.1.7
  '@types/turndown': 5.0.5
  '@vitejs/plugin-react': 4.7.0
  better-auth: 1.3.7
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: 1.1.1
  commander: 14.0.0
  date-fns: 4.1.0
  dotenv: 17.2.1
  drizzle-kit: 0.31.4
  drizzle-orm: 0.44.4
  drizzle-seed: 0.3.1
  embla-carousel-react: 8.6.0
  input-otp: 1.4.2
  lucide-react: 0.536.0
  next-themes: 0.4.6
  nodemailer: 7.0.5
  pg: 8.16.3
  postcss: 8.5.6
  prompts: 2.4.2
  react: 19.1.1
  react-aria-components: 1.12.1
  react-day-picker: 9.9.0
  react-dom: 19.1.1
  react-email: 4.2.8
  react-markdown: 9.0.1
  react-resizable-panels: 3.0.5
  recharts: 2.15.4
  sonner: 2.0.7
  tailwind-merge: 3.3.1
  tailwindcss: 4.1.11
  turndown: 7.1.2
  tw-animate-css: 1.3.6
  typescript: 5.9.2
  ultracite: 5.2.5
  vaul: 1.1.2
  vite: npm:rolldown-vite@7.1.5
  vite-tsconfig-paths: 5.1.4
  zod: 4.0.17

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
