packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': 2.1.3
  '@radix-ui/react-select': 2.2.5
  '@radix-ui/react-slot': 1.2.3
  '@react-email/components': 0.5.0
  '@react-email/preview-server': 4.2.8
  '@tailwindcss/postcss': 4.1.11
  '@tanstack/react-router': 1.130.12
  '@tanstack/react-start': 1.130.15
  '@types/node': 24.2.1
  '@types/nodemailer': 6.4.17
  '@types/pg': 8.15.5
  '@types/react': 19.1.9
  '@types/react-dom': 19.1.7
  '@vitejs/plugin-react': 4.7.0
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  dotenv: 17.2.1
  drizzle-kit: 0.31.4
  drizzle-orm: 0.44.4
  lucide-react: 0.536.0
  nodemailer: 7.0.5
  pg: 8.16.3
  postcss: 8.5.6
  react: 19.1.1
  react-dom: 19.1.1
  react-email: 4.2.8
  tailwind-merge: 3.3.1
  tailwindcss: 4.1.11
  tw-animate-css: 1.3.6
  typescript: 5.9.2
  ultracite: 5.1.2
  vite: 7.0.6
  vite-tsconfig-paths: 5.1.4
  zod: 4.0.17

ignoredBuiltDependencies:
  - sharp

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
