import { createFileRoute } from '@tanstack/react-router'
import ContactForm from '@/components/contact-form'

// @ts-expect-error Route types will be regenerated by TanStack Start (routeTree.gen.ts)
export const Route = createFileRoute('/contact')({
  component: () => (
    <main className="min-h-screen bg-black text-emerald-500">
      <div className="py-12">
        <ContactForm />
      </div>
    </main>
  ),
})
